# Generated by Django 4.2.2 on 2023-10-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('amenities', models.TextField(choices=[('Balcony', 'Balcony'), ('Gym', 'Gym'), ('Swimming Pool', 'Swimming Pool')])),
                ('status', models.TextField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')])),
                ('house_type', models.PositiveIntegerField(choices=[('Single_room', 'Singleroom'), ('Bedsitter', 'Bedsitter'), ('One bedroom', 'One bedroom'), ('Two bedroom', 'Two bedroom'), ('Three bedroom', 'Three bedroom'), ('Four bedroom', 'Four bedroom'), ('Studio', 'Studio'), ('commercial shops', 'commercial shops')])),
                ('size', models.PositiveIntegerField(choices=[('STANDARD', 'STANDARD'), ('Spacious', 'Spacious')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
