# Generated by Django 4.2.2 on 2023-06-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('amenities', models.TextField()),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('references', models.TextField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.lease_model')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.lease_model')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.property_model')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.tenant_model')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.property_model')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.tenant_model')),
            ],
        ),
        migrations.AddField(
            model_name='lease_model',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.property_model'),
        ),
        migrations.AddField(
            model_name='lease_model',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.tenant_model'),
        ),
        migrations.CreateModel(
            name='Invoice_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.lease_model')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.property_model')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.tenant_model')),
            ],
        ),
    ]
