# Generated by Django 4.2.2 on 2023-06-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant_model',
            name='references',
        ),
        migrations.AddField(
            model_name='tenant_model',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
