# Generated by Django 4.2.2 on 2023-06-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_remove_tenant_model_references_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease_model',
            name='tenant',
        ),
        migrations.AddField(
            model_name='lease_model',
            name='tenant',
            field=models.ManyToManyField(to='coreApp.tenant_model'),
        ),
    ]
