# Generated by Django 4.2.2 on 2023-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_alter_property_model_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_model',
            name='amenities',
            field=models.TextField(choices=[('Balcony', 'Balcony'), ('Gym', 'Gym'), ('SwimmingPool', 'SwimmingPool')]),
        ),
        migrations.AlterField(
            model_name='property_model',
            name='house_type',
            field=models.PositiveIntegerField(choices=[('Singleroom', 'Singleroom'), ('Bedsitter', 'Bedsitter'), ('Onebedroom', 'Onebedroom'), ('Twobedroom', 'Twobedroom'), ('Threebedroom', 'Threebedroom'), ('Fourbedroom', 'Fourbedroom'), ('Studio', 'Studio'), ('Commercialshops', 'Commercialshops')]),
        ),
    ]
