# Generated by Django 4.2.2 on 2023-06-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_remove_lease_model_tenant_lease_model_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease_model',
            name='tenant',
        ),
        migrations.AddField(
            model_name='lease_model',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreApp.tenant_model'),
        ),
    ]
