# Generated by Django 4.2.2 on 2023-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_alter_property_model_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_model',
            name='house_type',
            field=models.CharField(choices=[('Singleroom', 'Singleroom'), ('Bedsitter', 'Bedsitter'), ('Onebedroom', 'Onebedroom'), ('Twobedroom', 'Twobedroom'), ('Threebedroom', 'Threebedroom'), ('Fourbedroom', 'Fourbedroom'), ('Studio', 'Studio'), ('Commercialshops', 'Commercialshops')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property_model',
            name='size',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('Spacious', 'Spacious')], max_length=50),
        ),
    ]
