# Generated by Django 4.2.2 on 2023-06-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_remove_lease_model_tenant_lease_model_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_model',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreApp.lease_model'),
        ),
    ]
