# Generated by Django 4.2.2 on 2023-10-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0005_alter_property_model_house_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_model',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='property_model',
            name='start_date',
        ),
    ]
