# Generated by Django 4.2.2 on 2023-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0005_alter_tenant_model_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant_model',
            name='reference',
        ),
        migrations.AddField(
            model_name='tenant_model',
            name='references',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lease_model',
            name='tenant',
            field=models.TextField(default=22, verbose_name='Tenant_model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant_model',
            name='lease',
            field=models.TextField(default=3, verbose_name='Lease_model'),
            preserve_default=False,
        ),
    ]
