# Generated by Django 4.2.2 on 2023-10-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0006_remove_property_model_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_model',
            old_name='name',
            new_name='property_name',
        ),
    ]
