# Generated by Django 4.2.2 on 2023-06-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0006_remove_tenant_model_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease_model',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.tenant_model'),
        ),
        migrations.AlterField(
            model_name='tenant_model',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.lease_model'),
        ),
    ]
