# Generated by Django 4.2.2 on 2023-07-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0007_alter_lease_model_tenant_alter_tenant_model_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_model',
            name='amenities',
            field=models.TextField(choices=[('balcony', 'Balcony'), ('gym', 'Gym'), ('pool', 'Swimming Pool')]),
        ),
    ]
