# Generated by Django 4.2.2 on 2023-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0008_alter_property_model_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest_model',
            name='property',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest_model',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payment_model',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='payment_model',
            name='property',
        ),
        migrations.RemoveField(
            model_name='payment_model',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='lease_model',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property_model',
            name='amenities',
            field=models.TextField(choices=[('Balcony', 'Balcony'), ('Gym', 'Gym'), ('Swimming Pool', 'Swimming Pool')]),
        ),
        migrations.AlterField(
            model_name='property_model',
            name='status',
            field=models.TextField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')]),
        ),
        migrations.DeleteModel(
            name='Invoice_model',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest_model',
        ),
        migrations.DeleteModel(
            name='Payment_model',
        ),
    ]
