# Generated by Django 4.2.2 on 2023-08-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0009_remove_maintenancerequest_model_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant_model',
            name='lease',
        ),
        migrations.AddField(
            model_name='tenant_model',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.property_model'),
        ),
        migrations.DeleteModel(
            name='Lease_model',
        ),
    ]
