# Generated by Django 4.2.2 on 2023-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0010_remove_tenant_model_lease_tenant_model_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_model',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
