# Generated by Django 4.2.2 on 2023-07-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
