# Generated by Django 4.2.2 on 2023-07-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
