# Generated by Django 4.2.2 on 2023-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0006_alter_customuser_is_staff_alter_customuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
