# Generated by Django 4.2.2 on 2023-07-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0007_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
